# Generated by Django 5.0 on 2025-07-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stylist',
            name='specialization',
            field=models.TextField(blank=True),
        ),
    ]
