# Generated by Django 5.0 on 2025-07-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reschedule_requested',
            field=models.BooleanField(default=False),
        ),
    ]
