# Generated by Django 5.0 on 2025-07-24 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_reschedule_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='reschedule_requested',
        ),
    ]
