# Generated by Django 5.0 on 2025-07-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons_and_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_upto',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
